name: Build

on: [push, pull_request]

jobs:
  build_dart_packages:
    runs-on: ubuntu-latest

    container:
      image: google/dart:${{ matrix.version }}

    strategy:
      matrix:
        package: ["timeago"]
        version: ["latest"]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ${{ matrix.package }}
        run: pub get

      - name: Analyze
        working-directory: ${{ matrix.package }}
        run: dartanalyzer --fatal-infos --fatal-warnings .

      - name: Run tests
        working-directory: ${{ matrix.package }}
        run: pub run test
